#!/usr/bin/env python3
"""
Regenerates deadcells/src/game/_MatchInclude.hx and deadcells/build.match.hxml.

Haxe only type-checks (let alone compiles) what's reachable from -main. Most
of Dead Cells isn't wired into Boot's real game loop yet, so most classes
never get typed at all when built normally - they're not "dead code
eliminated," they're never even considered, which makes them permanently
absent from the compiled output and thus unscoreable by tools/diff_opcodes.py,
regardless of how correct their decompilation is.

Fix: force every top-level game package (via haxe.macro.Compiler.include,
which recursively types a whole directory) and every flat root-level class
(via a null-cast, since `include` expects a package/directory, not a single
file - see the module docstring history for why this two-part approach was
needed) to be typed and kept (-dce no, so DCE doesn't then strip fields from
classes that got typed but aren't actually called from anywhere).

Regenerate this after adding/removing a top-level class or package under
deadcells/src/game:
    uv run tools/gen_match_include.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from diff_opcodes import ROOT, SRC, game_top_level_names  # noqa: E402


def main() -> None:
    names = sorted(game_top_level_names())
    flat_classes = [n for n in names if (SRC / f"{n}.hx").is_file()]
    # haxe.macro.Compiler.include()'s directory scan enforces "package name must
    # start with a lowercase character" more strictly than normal typing does -
    # skip the couple of underscore-prefixed quirk packages (_Data, _Stats; see
    # docs/notes.md history on the crashlink merge) rather than fight the macro.
    # They stay real game code, just not force-included yet.
    packages = [n for n in names if (SRC / n).is_dir() and not n.startswith("_")]

    include_hx = SRC / "_MatchInclude.hx"
    casts = "\n".join(f"            cast (null: {name})," for name in flat_classes)
    include_hx.write_text(
        f"""\
// Generated by tools/gen_match_include.py - do not hand-edit, and don't count
// this file itself as something to decompile (it's project tooling, not game code).
class _MatchInclude {{
    static function keep(): Array<Dynamic> {{
        return [
{casts}
        ];
    }}
    static function main(): Void {{}}
}}
"""
    )

    # Scope every include() to our own source tree explicitly (classPaths arg) -
    # without this, include() scans ALL classpaths, and a package name that
    # happens to collide with a vendor library's own package (e.g. our
    # `tools.pak` vs. heaps' own `tools.mikktspace`) pulls in unrelated,
    # sometimes malformed vendor modules we have no business touching.
    macro_includes = "\n".join(f"--macro include('{name}', true, null, ['src/game'])" for name in packages)
    hxml = ROOT / "deadcells" / "build.match.hxml"
    hxml.write_text(
        f"""\
_base_no_main.hxml
-D windowSize=1280x720
-hl bin/client.hl
-lib hlsdl
-dce no
-main _MatchInclude
{macro_includes}
"""
    )
    print(f"wrote {include_hx} ({len(flat_classes)} classes) and {hxml} ({len(packages)} packages)")


if __name__ == "__main__":
    main()
